name: 'dbt_snap_join'
version: '1.0.0'

profile: snap

model-paths: ["models"]
seed-paths: ["seeds"]
macro-paths: ["macros"]

models:
  +tags: 'snap_join_example'
  +enabled: false

seeds:
  +tags: 'snap_join_example'
  +enabled: false
